apiVersion: v1
kind: Service
metadata:
  labels:
    app: action-server
  name: action-server
spec:
  ports:
    - port: 5055
  type: NodePort
  selector:
    app: action-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: action-server
  name: action-server
spec:
  selector:
    matchLabels:
      app: action-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: action-server
    spec:
      containers:
        - image: '172.30.3.211:30003/rasa-cn:latest'
          command: ["rasa","run","actions","--actions","actions"]
          imagePullPolicy: "Always"
          name: action-server
          ports:
            - containerPort: 5055
          resources: {}
          stdin: true
          tty: true
      imagePullSecrets:
        - name: docker-secret
      restartPolicy: Always
