apiVersion: v1
kind: Service
metadata:
  labels:
    app: action-server
  name: action-server
spec:
  ports:
    - name: "5055"
      port: 5055
      targetPort: 5055
  selector:
    app: action-server

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: action-server
spec:
  rules:
    - host: rasa.leandata.top
      http:
        paths:
          - backend:
              serviceName: action-server
              servicePort: 5055

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: action-server
  name: action-server
spec:
  selector:
    matchLabels:
      app: action-server
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: action-server
    spec:
      containers:
        - image: '172.30.3.211:30003/rasa-cn:latest'
          imagePullPolicy: "Always"
          name: action-server
          ports:
            - containerPort: 5055
          resources: {}
          stdin: true
          tty: true
      imagePullSecrets:
        - name: docker-secret
      restartPolicy: Always
