# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh
#pipeline: supervised_embeddings
pipeline:
  - name: "third_party_tokenizer.ThirdPartyTokenizer"
    third_party_service_endpoint: http://tokenize-api.leandata.top/tokenize
    type: tokenizer
  - name: "RegexFeaturizer"
  - name: "third_party_extractor.ThirdPartyEntityExtractor"
    third_party_service_endpoint: http://tokenize-api.leandata.top/tokenize
    type: extractor
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"

policies:
  - name: KerasPolicy
  - name: MappingPolicy
